// function to generate markdown for README - takes the questions and builds the markdown file
function generateMarkdown(data) {
    return `
<h2>${data.title}</h2>

![badge](https://img.shields.io/badge/license-${data.license}-brightgreen)<br />
## Description
   ${data.description}
## Table of Contents
- [Description](#description)
- [Installation](#installation)
- [Usage](#usage)
- [License](#license)
- [Contributing](#contributing)
- [Tests](#tests)
- [Questions](#questions)
## Installation
    ${data.installation}
## Usage
    ${data.usage}
## License
![badge](https://img.shields.io/badge/license-${data.license}-brightgreen)
<br>
This application is covered under ${data.license} license agreements. 
## Contributing
   ${data.contributing}
## Tests
   ${data.tests}
## Repository
   ${data.repo}        
## Questions?
   ${data.questions}
<br>
My GitHub profile: [${data.username}](https://github.com/${data.username})
<br>
For any questions, please email me at: ${data.email}
<br>
## Additional Notes
This README was generated by [README-generator](https://github.com/nagck/readmegen)
  `;
}
  
module.exports = generateMarkdown;